# Generated by Django 5.1.3 on 2024-11-24 16:12

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HandlingUnitModel',
            fields=[
                ('id_hu', models.AutoField(primary_key=True, serialize=False)),
                ('pce', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('weight', models.DecimalField(decimal_places=2, max_digits=9)),
                ('weight_uom', models.CharField(max_length=2)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=6)),
                ('volume_uom', models.CharField(max_length=3)),
                ('is_active', models.BooleanField(default='True')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialModel',
            fields=[
                ('id_material', models.AutoField(primary_key=True, serialize=False)),
                ('material', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(regex='^[0-9A-Z]*$')])),
                ('description', models.CharField(max_length=200)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0.01000000000000000020816681711721685132943093776702880859375'))])),
                ('weight_uom', models.CharField(default='KG', max_length=2)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01000000000000000020816681711721685132943093776702880859375'))])),
                ('volume_uom', models.CharField(default='CDM', max_length=3)),
                ('created_by', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BinModel',
            fields=[
                ('id_bin', models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(regex='^[0-9A-Z-]*$')])),
                ('empty', models.BooleanField(default='True')),
                ('hu', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='bin_hu', to='app_apiwhs.handlingunitmodel')),
            ],
        ),
        migrations.AddField(
            model_name='handlingunitmodel',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_hu', to='app_apiwhs.materialmodel'),
        ),
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id_task', models.AutoField(primary_key=True, serialize=False)),
                ('created_by', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('destination_bin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_destination_bin', to='app_apiwhs.binmodel')),
                ('hu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_hu', to='app_apiwhs.handlingunitmodel')),
                ('source_bin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_source_bin', to='app_apiwhs.binmodel')),
            ],
        ),
    ]
