# Generated by Django 5.1.3 on 2024-11-24 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_apiwhs', '0002_alter_binmodel_hu'),
    ]

    operations = [
        migrations.AddField(
            model_name='binmodel',
            name='type',
            field=models.CharField(default='ST', max_length=3),
        ),
        migrations.AddField(
            model_name='binmodel',
            name='verification_field',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
