# Generated by Django 5.1.3 on 2024-11-24 17:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_apiwhs', '0004_alter_binmodel_id_bin'),
    ]

    operations = [
        migrations.AddField(
            model_name='binmodel',
            name='created_by',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='binmodel',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
