# Generated by Django 5.1.3 on 2024-11-25 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_apiwhs', '0005_binmodel_created_by_binmodel_created_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='handlingunitmodel',
            old_name='pce',
            new_name='quantity',
        ),
    ]
