# Generated by Django 5.1.3 on 2024-11-25 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_apiwhs', '0006_rename_pce_handlingunitmodel_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='handlingunitmodel',
            old_name='id_hu',
            new_name='id_handlingunit',
        ),
    ]
