# Generated by Django 5.1.3 on 2024-11-25 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_apiwhs', '0007_rename_id_hu_handlingunitmodel_id_handlingunit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='binmodel',
            old_name='hu',
            new_name='handlingunit',
        ),
    ]
